#pragma once

// Game settings
#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 512
#define RESOURCES_FILEPATH "..Resources/"

// Sound
#define BGM_MAIN_MENU_FILEPATH RESOURCES_FILEPATH"Audio/somnus.ogg"
#define BGM_LEVEL_FILEPATH RESOURCES_FILEPATH"Audio/abomination.ogg"
#define SOUND_EFFECT_CONFIRM_FILEPATH RESOURCES_FILEPATH"Audio/confirm.ogg"
#define SOUND_EFFECT_CANCEL_FILEPATH RESOURCES_FILEPATH"Audio/cancel.ogg"
#define SOUND_EFFECT_SELECT_FILEPATH RESOURCES_FILEPATH"Audio/select.ogg"

// Fonts
#define CHIARO_FONT RESOURCES_FILEPATH"Fonts/FOT-ChiaroStd-B.otf"

// Game Screen
#define PLAYER_SPRITE_ALM_FILEPATH RESOURCES_FILEPATH"Graphics/alm_move.png"
#define PLAYER_SPRITE_ROBIN_FILEPATH RESOURCES_FILEPATH"Graphics/robin_move.png"
#define PROJECTILE_SPRITE_FILEPATH RESOURCES_FILEPATH"Graphics/projectile.png"
#define ENEMY_SPRITE_BONE_FILEPATH RESOURCES_FILEPATH"Graphics/bonewalker_move.png"
#define TILESET_FILEPATH RESOURCES_FILEPATH"Graphics/tileset.png"

// Level data
#define DEMO_FILEPATH RESOURCES_FILEPATH"Levels/demo.txt"
#define LEVEL_ONE_FILEPATH RESOURCES_FILEPATH"Levels/level1.txt"
#define LEVEL_TWO_FILEPATH RESOURCES_FILEPATH"Levels/level2.txt"
#define LEVEL_ONE_ENEMY_DATA_FILEPATH RESOURCES_FILEPATH"Levels/enemyData1.txt"
#define LEVEL_TWO_ENEMY_DATA_FILEPATH RESOURCES_FILEPATH"Levels/enemyData2.txt"